### ISSUE TITLE
【小程序审核问题】请问留言功能是怎么过审的？不会被拒吗？

### ISSUE THREAD

**Issue by felbry** [wforguo/wedding-app#24]
这个审核是真滴恶心人呀

**Comment by web-farmer** [comment]
可以去尝试把留言和视频关掉去审核，过了再打开，数据库有对应字段可以控制的
需要修改的数据库及对应的字段如下，
wedding_invite ---> msg
wedding_video ---> videoVisible

![image](https://user-images.githubusercontent.com/23009078/176326154-419bc423-3bfa-4135-bf8d-27a317b47595.png)

![image](https://user-images.githubusercontent.com/23009078/176326213-5c75d15d-c048-4454-93e3-91e8454944fc.png)

**Comment by felbry** [comment]
> 可以去尝试把留言和视频关掉去审核，过了再打开，数据库有对应字段可以控制的 需要修改的数据库及对应的字段如下， wedding_invite ---> msg wedding_video ---> videoVisible
> 
> ![image](https://user-images.githubusercontent.com/23009078/176326154-419bc423-3bfa-4135-bf8d-27a317b47595.png)
> 
> ![image](https://user-images.githubusercontent.com/23009078/176326213-5c75d15d-c048-4454-93e3-91e8454944fc.png)

感谢！昨晚用了这个方法 确实是过了哈哈哈哈哈
